{"name": "新建人群", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[@id=\"rc-menu-uuid-01002-1-fatherMenu-1-popup\"]/li[2]/span\"}\n  (Session info: chrome=126.0.6478.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x000000010979b6c8 chromedriver + 6149832\n1   chromedriver                        0x0000000109792cea chromedriver + 6114538\n2   chromedriver                        0x000000010921fd5c chromedriver + 400732\n3   chromedriver                        0x000000010926caa5 chromedriver + 715429\n4   chromedriver                        0x000000010926cbf1 chromedriver + 715761\n5   chromedriver                        0x00000001092b1dd4 chromedriver + 998868\n6   chromedriver                        0x000000010928fcdd chromedriver + 859357\n7   chromedriver                        0x00000001092af0db chromedriver + 987355\n8   chromedriver                        0x000000010928fa53 chromedriver + 858707\n9   chromedriver                        0x000000010925f6d5 chromedriver + 661205\n10  chromedriver                        0x000000010925ff6e chromedriver + 663406\n11  chromedriver                        0x000000010975cd00 chromedriver + 5893376\n12  chromedriver                        0x00000001097624cc chromedriver + 5915852\n13  chromedriver                        0x000000010973e8c4 chromedriver + 5769412\n14  chromedriver                        0x0000000109762f99 chromedriver + 5918617\n15  chromedriver                        0x000000010972fed4 chromedriver + 5709524\n16  chromedriver                        0x0000000109783018 chromedriver + 6049816\n17  chromedriver                        0x00000001097831d7 chromedriver + 6050263\n18  chromedriver                        0x000000010979289e chromedriver + 6113438\n19  libsystem_pthread.dylib             0x00007ff816ca518b _pthread_start + 99\n20  libsystem_pthread.dylib             0x00007ff816ca0ae3 thread_start + 15", "trace": "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"943383535e506be9bba9190d7c787e14\")>\ndata = {'newAudience': {'populationDefinition': '自动化回归', 'populationName': 'cjw自动化回归测试'}, 'passwd': 'Cjw19951008.', 'selected': ['用户测试标签', '待选择', '否', '下拉', '多选'], 'username': 'cuijianwei', ...}\n\n    @allure.title(\"新建人群\")\n    @allure.story(\"典型场景\")\n    @allure.severity(\"critical\")\n    @pytest.mark.parametrize('data', load_yaml(r\"/Users/koolearn/cuijianwei/pytest-allure-ui/Data/testcase_data/nvwa.yaml\"))\n    def test_04(browser, data):\n        labelBuild = New_Audience(browser)\n>       labelBuild.new_audience(data)\n\nTestCase/test_case_nvwa.py:56: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nPage/nvwa/nvwa_new_audience.py:22: in new_audience\n    self.ele_value_normal(*self.Button.group).click()\nKeyWord/Browser.py:163: in ele_value_normal\n    return self.__d.find_element(by, value)\n../PyProject/LinkHolo/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:741: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n../PyProject/LinkHolo/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fafd67fbe20>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"no such element: Unable to locate element: {\\...7ff816ca518b _pthread_start + 99\\\\n20  libsystem_pthread.dylib             0x00007ff816ca0ae3 thread_start + 15\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[@id=\"rc-menu-uuid-01002-1-fatherMenu-1-popup\"]/li[2]/span\"}\nE         (Session info: chrome=126.0.6478.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       0   chromedriver                        0x000000010979b6c8 chromedriver + 6149832\nE       1   chromedriver                        0x0000000109792cea chromedriver + 6114538\nE       2   chromedriver                        0x000000010921fd5c chromedriver + 400732\nE       3   chromedriver                        0x000000010926caa5 chromedriver + 715429\nE       4   chromedriver                        0x000000010926cbf1 chromedriver + 715761\nE       5   chromedriver                        0x00000001092b1dd4 chromedriver + 998868\nE       6   chromedriver                        0x000000010928fcdd chromedriver + 859357\nE       7   chromedriver                        0x00000001092af0db chromedriver + 987355\nE       8   chromedriver                        0x000000010928fa53 chromedriver + 858707\nE       9   chromedriver                        0x000000010925f6d5 chromedriver + 661205\nE       10  chromedriver                        0x000000010925ff6e chromedriver + 663406\nE       11  chromedriver                        0x000000010975cd00 chromedriver + 5893376\nE       12  chromedriver                        0x00000001097624cc chromedriver + 5915852\nE       13  chromedriver                        0x000000010973e8c4 chromedriver + 5769412\nE       14  chromedriver                        0x0000000109762f99 chromedriver + 5918617\nE       15  chromedriver                        0x000000010972fed4 chromedriver + 5709524\nE       16  chromedriver                        0x0000000109783018 chromedriver + 6049816\nE       17  chromedriver                        0x00000001097831d7 chromedriver + 6050263\nE       18  chromedriver                        0x000000010979289e chromedriver + 6113438\nE       19  libsystem_pthread.dylib             0x00007ff816ca518b _pthread_start + 99\nE       20  libsystem_pthread.dylib             0x00007ff816ca0ae3 thread_start + 15\n\n../PyProject/LinkHolo/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: NoSuchElementException"}, "steps": [{"name": "新建人群", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[@id=\"rc-menu-uuid-01002-1-fatherMenu-1-popup\"]/li[2]/span\"}\n  (Session info: chrome=126.0.6478.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x000000010979b6c8 chromedriver + 6149832\n1   chromedriver                        0x0000000109792cea chromedriver + 6114538\n2   chromedriver                        0x000000010921fd5c chromedriver + 400732\n3   chromedriver                        0x000000010926caa5 chromedriver + 715429\n4   chromedriver                        0x000000010926cbf1 chromedriver + 715761\n5   chromedriver                        0x00000001092b1dd4 chromedriver + 998868\n6   chromedriver                        0x000000010928fcdd chromedriver + 859357\n7   chromedriver                        0x00000001092af0db chromedriver + 987355\n8   chromedriver                        0x000000010928fa53 chromedriver + 858707\n9   chromedriver                        0x000000010925f6d5 chromedriver + 661205\n10  chromedriver                        0x000000010925ff6e chromedriver + 663406\n11  chromedriver                        0x000000010975cd00 chromedriver + 5893376\n12  chromedriver                        0x00000001097624cc chromedriver + 5915852\n13  chromedriver                        0x000000010973e8c4 chromedriver + 5769412\n14  chromedriver                        0x0000000109762f99 chromedriver + 5918617\n15  chromedriver                        0x000000010972fed4 chromedriver + 5709524\n16  chromedriver                        0x0000000109783018 chromedriver + 6049816\n17  chromedriver                        0x00000001097831d7 chromedriver + 6050263\n18  chromedriver                        0x000000010979289e chromedriver + 6113438\n19  libsystem_pthread.dylib             0x00007ff816ca518b _pthread_start + 99\n20  libsystem_pthread.dylib             0x00007ff816ca0ae3 thread_start + 15\n\n", "trace": "  File \"/Users/koolearn/cuijianwei/PyProject/LinkHolo/.venv/lib/python3.9/site-packages/allure_commons/_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"/Users/koolearn/cuijianwei/pytest-allure-ui/Page/nvwa/nvwa_new_audience.py\", line 22, in new_audience\n    self.ele_value_normal(*self.Button.group).click()\n  File \"/Users/koolearn/cuijianwei/pytest-allure-ui/KeyWord/Browser.py\", line 163, in ele_value_normal\n    return self.__d.find_element(by, value)\n  File \"/Users/koolearn/cuijianwei/PyProject/LinkHolo/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Users/koolearn/cuijianwei/PyProject/LinkHolo/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/koolearn/cuijianwei/PyProject/LinkHolo/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "text", "value": "{'username': 'cuijianwei', 'passwd': 'Cjw19951008.', 'verificationCode': 123456, 'selected': ['用户测试标签', '待选择', '否', '下拉', '多选'], 'newAudience': {'populationName': 'cjw自动化回归测试', 'populationDefinition': '自动化回归'}}"}], "start": 1719567521690, "stop": 1719567521738}, {"name": "用例执行失败截图===", "status": "passed", "attachments": [{"name": "失败截图", "source": "5bd5c8f8-120d-4845-972a-94fc2955b9c6-attachment.png", "type": "image/png"}], "start": 1719567521859, "stop": 1719567522167}], "parameters": [{"name": "data", "value": "{'username': 'cuijianwei', 'passwd': 'Cjw19951008.', 'verificationCode': 123456, 'selected': ['用户测试标签', '待选择', '否', '下拉', '多选'], 'newAudience': {'populationName': 'cjw自动化回归测试', 'populationDefinition': '自动化回归'}}"}], "start": 1719567521690, "stop": 1719567521741, "uuid": "0dfbc952-48ed-4d28-a369-24d5d86d3691", "historyId": "b07306742a0536fca473b58f3ca2caa3", "testCaseId": "24b0ae0d194387c7ea69fbfaa2a60959", "fullName": "TestCase.test_case_nvwa#test_04", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "典型场景"}, {"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_case_nvwa"}, {"name": "host", "value": "cuijianweiMacPro"}, {"name": "thread", "value": "7010-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_case_nvwa"}]}