{"name": "打开百度首页，从【更多】进入【百度翻译】进行翻译", "status": "passed", "description": "\n        01 打开百度首页\n        02 输入内容 进行搜索\n        03 回退到百度首页\n        04 首页点击 更多\n        05 切换到 更多 页签\n        06 更多 页面点击 翻译\n        07 切换到 翻译 页签\n        08 关闭展示页、输入内容 进行翻译\n    ", "steps": [{"name": "进入百度首页", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=111.0.5563.65)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x00EEDCE3]\n\t(No symbol) [0x00E839D1]\n\t(No symbol) [0x00D94DA8]\n\t(No symbol) [0x00D7D0D3]\n\t(No symbol) [0x00DDEA8B]\n\t(No symbol) [0x00DED093]\n\t(No symbol) [0x00DDACC6]\n\t(No symbol) [0x00DB6F68]\n\t(No symbol) [0x00DB80CD]\n\tGetHandleVerifier [0x01163832+2506274]\n\tGetHandleVerifier [0x01199794+2727300]\n\tGetHandleVerifier [0x0119E36C+2746716]\n\tGetHandleVerifier [0x00F96690+617600]\n\t(No symbol) [0x00E8C712]\n\t(No symbol) [0x00E91FF8]\n\t(No symbol) [0x00E920DB]\n\t(No symbol) [0x00E9C63B]\n\tBaseThreadInitThunk [0x76FD00F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x771D7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x771D7B8E+238]\n\n", "trace": "  File \"D:\\Pycharm\\selenium+pytest框架\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"D:\\Pycharm\\selenium+pytest框架\\Page\\test_baidu\\baidu_home.py\", line 20, in open_home\n    self.open(self.url)\n  File \"D:\\Pycharm\\selenium+pytest框架\\KeyWord\\Browser.py\", line 32, in open\n    self.__wait.until(ec.url_contains(url))\n  File \"D:\\Pycharm\\selenium+pytest框架\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 86, in until\n    value = method(self._driver)\n  File \"D:\\Pycharm\\selenium+pytest框架\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 83, in _predicate\n    return url in driver.current_url\n  File \"D:\\Pycharm\\selenium+pytest框架\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 530, in current_url\n    return self.execute(Command.GET_CURRENT_URL)[\"value\"]\n  File \"D:\\Pycharm\\selenium+pytest框架\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Pycharm\\selenium+pytest框架\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1679755143730, "stop": 1679755144693}, {"name": "用例执行失败截图===", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=111.0.5563.65)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x00EEDCE3]\n\t(No symbol) [0x00E839D1]\n\t(No symbol) [0x00D94DA8]\n\t(No symbol) [0x00D7D0D3]\n\t(No symbol) [0x00DDEA8B]\n\t(No symbol) [0x00DED093]\n\t(No symbol) [0x00DDACC6]\n\t(No symbol) [0x00DB6F68]\n\t(No symbol) [0x00DB80CD]\n\tGetHandleVerifier [0x01163832+2506274]\n\tGetHandleVerifier [0x01199794+2727300]\n\tGetHandleVerifier [0x0119E36C+2746716]\n\tGetHandleVerifier [0x00F96690+617600]\n\t(No symbol) [0x00E8C712]\n\t(No symbol) [0x00E91FF8]\n\t(No symbol) [0x00E920DB]\n\t(No symbol) [0x00E9C63B]\n\tBaseThreadInitThunk [0x76FD00F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x771D7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x771D7B8E+238]\n\n", "trace": "  File \"D:\\Pycharm\\selenium+pytest框架\\conftest.py\", line 41, in pytest_runtest_makereport\n    allure.attach(driver.get_screenshot_as_png(), \"失败截图\", allure.attachment_type.PNG)\n  File \"D:\\Pycharm\\selenium+pytest框架\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 926, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"D:\\Pycharm\\selenium+pytest框架\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 937, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"D:\\Pycharm\\selenium+pytest框架\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Pycharm\\selenium+pytest框架\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1679755148917, "stop": 1679755148919}], "parameters": [{"name": "text", "value": "'语文'"}, {"name": "text1", "value": "'语文'"}], "start": 1679755143730, "stop": 1679755144742, "uuid": "5a983dde-f6d3-4bc2-a46c-d2bae84dec73", "historyId": "58b75f738749a691da9c63b30ce95aa1", "testCaseId": "6ca9647a38b62328b10ff66055804c57", "fullName": "TestCase.test_case_01#test_01"}